### ISSUE TITLE
Final result is not final (iOS, plugin version 2.7.0)

### ISSUE THREAD

**Issue by tamoyal** [csdcorp/speech_to_text#190]
I'm going to start the upgrade process but figured I would ask here in case this is a known solved bug or it may exist post upgrade. I'm currently on 2.7.0 but I see the latest version is 3.2.0

In my result listener (`onResult`) I wait for the result to be final by checking `result.finalResult` and if so, I stop listening. I invoke this by calling `speech.stop()` if I don't get any new results for 2 seconds. When that occurs, I print the JSON. Here is an example:
```
{alternates: [{recognizedWords: Yo se, confidence: 0.151}], finalResult: true}
```

However, I notice after some time, the log prints way more alternates:
```
[plugin] FinishRecognition true
[plugin] Encoded JSON result: {"alternates":[{"recognizedWords":"Yo se","confidence":0.018},{"recognizedWords":"Yo sé","confidence":0.018},{"recognizedWords":"Lo sé","confidence":0.005},{"recognizedWords":"O se","confidence":0.002},{"recognizedWords":"Lo se","confidence":0.004},{"recognizedWords":"Rose","confidence":0.065},{"recognizedWords":"José","confidence":0.024},{"recognizedWords":"Jose","confidence":0.06},{"recognizedWords":"No se","confidence":0.002},{"recognizedWords":"No sé","confidence":0.002}],"finalResult":true}
```
which I do have access to in the `onResult` callback but at that point I have already processed the results and moved on. Is there some other event I need to wait for? I'm wondering if I'm using this incorrectly.

Thank you!

**Comment by tamoyal** [comment]
I just confirmed the same issue exists in version `3.1.0`

**Comment by sowens-csd** [comment]
I think this is a real issue. There's something odd about the way final results are coming back, or not coming back, from iOS. I did do some work on the problem and couldn't get any traction so to work around the problem I force a 'final' result after 100 ms if I haven't seen one from the OS. It seems likely to me that's what you're seeing as your first final result. 

It looks like some time later the actual final result is coming back. I don't think I'd realized that was happening in my initial testing. Thanks for the input. I'm going to work on this issue in the 4.x series. In the meantime, you're not doing anything wrong in your usage of the plugin.

**Comment by tamoyal** [comment]
@sowens-csd Oh gotcha! Thank you for the fast response as always. [This link](https://developer.apple.com/forums/thread/63834) says `endAudio` forces final and maybe that is actually what they expect?

You are saying "you force a final result" after 100ms. Does that mean you do that internally in the library or you do in your code that uses the library?

I'm just wondering what my workaround might be ....do I wait for multiple `finalResult` calls? Or should I just wait the 100ms to see if something else comes back? It seems like you are able to detect this to some extent because the log has `FinishRecognition: true` and that's the actual result I want as it seems after that log statement is called, the real results come in.

**Comment by sowens-csd** [comment]
Yes, I do that 100 ms check internal to the library. Do you happen to have timestamps on the log results you are seeing that show the `FinishRecognition: true`? I'm curious what the delay is. 

Until you posted this I would have said all you needed to do is wait until you get a callback with `isFinal` true and you're done. However this new information makes that seem perhaps unwise, but I hate to suggest you do yet another work around on top of the horrible hack I've already put in there. 

Your `endAudio` suggestion is quite right. I just checked the existing plugin code and I see that I am doing that, however...there's an interesting bit of ordering in where I do it. I'm going to try a different order of execution and see if it helps. I'll let you know.

**Comment by sowens-csd** [comment]
I tried the world's shortest experiment on that and it didn't fail horribly but was inconclusive given the time I had to give it. I've committed a very small change to the repo so if you have a reproducible and have time to try it against the repo (main) version with that change that would be great.

**Comment by tamoyal** [comment]
@sowens-csd Thank you! I am going to give `main` a try but before I do, it's approximately 300ms between the first final result which is not final and the actual final result

**Comment by tamoyal** [comment]
@sowens-csd Amazing man ...looks like it's working but I'm going to test a bunch more to be sure and let you know

**Comment by tamoyal** [comment]
It seems like it works a bit better but @sowens-csd but I did just prove it's not fully working. I can still get a result with `isFinal` true where it is not the final result and the final result comes after. Let me know if I can give you any more debug info!

**Comment by tamoyal** [comment]
Sorry the pubspec download failed so I deleted previous comments and I'm testing again. I think because the dart lib is not in the root of the repo I have to do something funky.

**Comment by tamoyal** [comment]
Ok I confirmed that it's probably slightly better but definitely doesn't work 100% of the time.  Let me know if I can give you anymore debug info or help in any way, thanks!

**Comment by sowens-csd** [comment]
'probably slightly better' doesn't fill me with confidence. Well, that was likely far too simple to actually work. I'll keep looking.

In the meantime. One thing I could do pretty easily is to make my mitigation of the error optional or make the timer on the mitigation configurable. That way you would always get the true 'final' result although possibly after a longer delay. Perhaps I'm just being impatient and 300 ms for an accurate voice transcription just isn't that bad. It would only work if final results are always coming in after some time period but we could test that. Would that be better for your use case?

**Comment by sowens-csd** [comment]
I just committed another experiment. There's a new `finalTimeout` named Duration parameter on the `initialize` method. Set it to zero to disable that behaviour or set it really long if you want to ensure there's a backstop but you want to get the real results. Let me know how that behaves for you.

**Comment by tamoyal** [comment]
Sorry for the delay, wanted to give this a proper test! And yes, it seems to be working great. For now I put a 2 second timeout on there.

I think on your end as the provider of the API, it's better to be accurate than optimal. So I wouldn't worry about "300 ms for an accurate voice transcription." Whether it's 100ms or 10 entire seconds, I think the right thing to do is just be transparent on the response and yea, a timeout makes sense. I could have even seen you leaving that up to the consuming code but it's really nice to have.

Do you want me to test anything else?

Thanks so much again

**Comment by sowens-csd** [comment]
Thanks for letting me know. Given this result I'm going to default it to a far longer value and change the documentation. I've released the 3.2.0 version with this change to pub.dev. Development work is move over to the null safe version after this. Thanks for the help in tracking this down!
